### PR TITLE
Add `analyzadyration` flag and delete `timeout` option

### PR DESCRIPTION
**Pull request by oleh-poberezhets**
- Add stream `-analyzeduration` option

### CODE REVIEW

**Comment by WoZ** [comment]
Also, I think that we may still use `timeoutInSec` in configs but apply it only for rtmp, hls, http, dash streams and ignore it with notice for protocols that don't support any `timeot`-like options.

**Comment by OlegPoberegets** [comment]
1. I agree with you about `timeout` parameter for all protocols. But it has a different impact on each protocol and external library.
2. How I found a problem with `timeout` parameter:
I ran a default FFprobe build (it use native FFmpeg RTMP protocol) with args:
`-loglevel info -i "rtmp://host:port/app/ingest/playpath timeout=5"`

I saw the message in logs:
`[rtmp @ 0x18a3600] Detected librtmp style URL parameters, these aren't supported by the libavformat internal RTMP handler currently enabled. See the documentation for the correct way to pass parameters.`

For FFmpeg native RTMP protocol the accepted parameters are:
> **listen**
Act as a server, listening for an incoming connection.
**timeout**
Maximum time to wait for the incoming connection. Implies **listen**.

_But FFprobe does not act as a server. And `video-quality-tools` doesn't use **listen** parameter _

Next, see [FFmpeg librtmp](https://www.ffmpeg.org/ffmpeg-protocols.html#toc-librtmp-rtmp_002c-rtmpe_002c-rtmps_002c-rtmpt_002c-rtmpte) and [man librtmp](https://linux.die.net/man/3/librtmp)
> options contains a list of space-separated options of the form key=val.

And it is the description for "librtmp" options `timeout=5`, which mean:
> **timeout**=num
Timeout the session after num seconds without receiving any data from the server. The default is 120.

**That's why `timeoutInSec` work only for RTMP streams and FFprobe build with "–enable-librtmp"**

3. I agree that `analyzeduration` has another purpose than `timeoutInSec`

**Comment by WoZ** [comment]
@oleh-poberezhets may we use "internal" mechanism to detect timeouts? Just to use node to check timeouts, not ffmpeg? I remember that it was my point at the beginning of the project and @PavloKhilko investigated `timeout` option and we stopped with that option.

We may refactor our logic and may make it lib/protocol agnostic.

**Comment by oleh-poberezhets** [comment]
HTTP based protocols have `timeout` on TCP I/O operations. And we can add this option.

Of cause, everybody can set up an independent mechanism to detect a stream analyze timeouts.

But should be kept in mind that:
for RTMP protocol stream info processing include next timing phases:
**connection time** + **RTMP Handshaking** + **RTMP Play initializing** +  **analyzeduration** + **result output**

for HLS:
**connection time** + **load HLS playlist** + **load all chanks from playlist** + **analyzeduration** + **result output**

An independent timeout mechanism can`t know what phase is now and can stop analyze processing.
We can add an event about start analyzing for more accurate connection timeout detection.

**Comment by WoZ** [comment]
@oleh-poberezhets why do we need to know about phases?

**Comment by oleh-poberezhets** [comment]
@WoZ For setup timeout exactly on the phase of  **TCP connection + RTMP Handshaking**  in case of RTMP protocol but not for all FFprobe execution

**Comment by oleh-poberezhets** [comment]
Decision:
1. Replace `timeout` query option with `-rw_timeout`
2. Add `-analyzeduration` option.

But it will be 2 another PR

**Pull request closed without merging**
